plugins {
    id "com.android.application"
}

android {
    namespace "com.fm1.midibridge"
    compileSdk 34

    defaultConfig {
        applicationId "com.fm1.midibridge"
        minSdk 29
        targetSdk 34
        versionCode 4
        versionName "1.4"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
